laptop backup notes

diff --git a/docs/bin/backup-running-laptop b/docs/bin/backup-running-laptop
--- a/docs/bin/backup-running-laptop
+++ b/docs/bin/backup-running-laptop
@@ -5,17 +5,20 @@ set -eu -o pipefail
 #
 # 500GB in 78m on Sun 09 Oct 2022
 
-TARGET_DIR=${1:-}
+export TARGET_DIR=${1:-}
 if [[ -z $TARGET_DIR ]]; then
   echo >&2 "Usage: $0 TARGET_DIR"
   exit 1
-fi
-if ! [[ -d $TARGET_DIR ]]; then
+elif ! [[ -d $TARGET_DIR ]]; then
   echo >&2 "TARGET_DIR is not a directory ($TARGET_DIR}"
+  exit 1
+elif ! [[ $TARGET_DIR =~ $HOSTNAME ]]; then
+  echo >&2 "Error: Target directory must contain hostname."
+  echo >&2 "This is to reduce chance of overwriting another host's backup"
   exit 1
 fi
 
-SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+export SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
 # List all RPMS installed:
 
@@ -24,28 +27,37 @@ rpm -qa | sort > ~/rpm-qa-$(date +%Y%m%d)
 # [homedir excludes](https://raw.githubusercontent.com/rubo77/rsync-homedir-excludes/master/rsync-homedir-excludes.txt)
 # [--filter='-x security.selinux'](https://unix.stackexchange.com/a/648651/530692)
 
-# Sync entire root partition except ${HOME}/Videos
-time sudo rsync -aWHAXSv --info=progress2 --numeric-ids     \
-  --filter='-x security.selinux'                            \
-  --exclude-from="${SCRIPT_DIR}/rsync-homedir-excludes.txt" \
-  --exclude=/dev                                            \
-  --exclude=/home/libvirt \
-  --exclude=/home/m/.libvirt \
+homedir="$HOME"
+
+# (
+#   cd "${HOME}"
+#   # Sync $HOME except $Videos
+#   time rsync -naWHAXSv \
+#     --info=progress2 \
+#     --numeric-ids \
+#     --exclude-from="$SCRIPT_DIR/rsync-homedir-excludes.txt" \
+#     . "$TARGET_DIR/$homedir/"
+# )
+
+# Sync entire root partition except $HOME
+time sudo rsync -aWHAXSv \
+  --info=progress2 \
+  --numeric-ids \
+  --filter='-x security.selinux' \
+  --exclude="$homedir" \
+  --exclude=/dev \
   --exclude=/lost+found  \
-  --exclude=/home/m/.local/share/containers \
   --exclude=/media \
-  --exclude=/var/lib/docker \
   --exclude=/mnt \
   --exclude=/proc \
   --exclude=/run \
   --exclude=/sys \
   --exclude=/tmp \
-  --exclude=/home/m/Videos \
-  / "/$TARGET_DIR/$HOSTNAME-$(date +%Y%m%d)/"
+  --exclude=/var/lib/docker \
+  / "$TARGET_DIR"
 
 # Sync $HOME/Videos
 
 time sudo rsync -aWHAXSv --info=progress2 --numeric-ids \
   --filter='-x security.selinux' \
-  /home/m/Videos/ "${TARGET_DIR}/Videos/"
-
+  "${HOME}/Videos/" "${TARGET_DIR}/Videos/"
